// blogsData.js
export const blogsData = [
  {
    id: 2001,
    slug: "a-guide-to-sustainable-living-reduce-reuse-recycle",
    title: "A Guide to Sustainable Living: Reduce, Reuse, Recycle",
    category: "Lifestyle",
    thumbnail: "/src/assets/Blogs/a-guide-to-sustainable-living-reduce-reuse-recycle.webp",
    image: "/src/assets/Blogs/a-guide-to-sustainable-living-reuse-recycle.webp",
    date: "2026-02-15",
    author: "Eco Team",
    excerpt: "Discover practical ways to adopt a more sustainable lifestyle through the timeless principles of reduce, reuse, and recycle. Small changes can make a big environmental impact.",
    readTime: "8 min",
    tags: ["sustainability", "eco-friendly", "green living", "environment", "lifestyle", "zero waste"],
    content: "Full article content goes here... Start with why sustainability matters in 2026, then cover reduce tips (buy less, choose quality), reuse ideas (upcycling, second-hand shopping), recycle best practices, and daily habits to implement today."
  },
  {
    id: 2002,
    slug: "cooking-masterclass-creating-delicious-italian-pasta",
    title: "Cooking Masterclass: Creating Delicious Italian Pasta",
    category: "Cooking",
    thumbnail: "/src/assets/Blogs/cooking-masterclass-creating-delicious-italian-pasta.webp",
    image: "/src/assets/Blogs/cooking-masterclass-creating-delicious-italian-pasta.webp",
    date: "2026-01-28",
    author: "Chef Maria",
    excerpt: "Step-by-step masterclass on making authentic Italian pasta from scratch – dough, sauces, and classic dishes that will impress your family and friends.",
    readTime: "12 min",
    tags: ["cooking", "italian cuisine", "pasta recipes", "food", "homemade", "recipes", "culinary"],
    content: "Full article content goes here... Ingredients list, kneading technique, rolling/cutting pasta, classic sauces like carbonara, pesto, and marinara, plus tips for al dente perfection."
  },
  {
    id: 2003,
    slug: "exploring-the-wonders-of-modern-art-a-gallery-tour",
    title: "Exploring the Wonders of Modern Art: A Gallery Tour",
    category: "Art",
    thumbnail: "/src/assets/Blogs/exploring-the-wonders-of-modern-art-a-gallery-tour.webp",
    image: "/src/assets/Blogs/exploring-the-wonders-of-modern-art-a-gallery-tour.webp",
    date: "2026-03-01",
    author: "Art Enthusiast",
    excerpt: "Take a virtual tour through groundbreaking modern art pieces, artists, and galleries that are shaping contemporary creativity in 2026.",
    readTime: "10 min",
    tags: ["modern art", "gallery tour", "contemporary art", "artists", "culture", "creativity", "art history"],
    content: "Full article content goes here... Highlight key movements (abstract, pop, minimalism), featured artists, must-see galleries worldwide, and how modern art reflects society today."
  },
  {
    id: 2004,
    slug: "how-to-start-a-successful-e-commerce-business",
    title: "How to Start a Successful E-Commerce Business",
    category: "Business",
    thumbnail: "/src/assets/Blogs/how-to-start-a-successful-e-commerce-business.webp",
    image: "/src/assets/Blogs/how-to-start-a-successful-e-commerce-business.webp",
    date: "2026-02-10",
    author: "Business Guide",
    excerpt: "From idea to launch: a complete step-by-step guide to building and scaling your own profitable online store in today's digital market.",
    readTime: "15 min",
    tags: ["e-commerce", "online business", "startup", "entrepreneurship", "dropshipping", "shopify", "digital marketing"],
    content: "Full article content goes here... Niche selection, platform choices (Shopify, WooCommerce), product sourcing, marketing strategies, SEO, payment setup, and scaling tips."
  },
  {
    id: 2005,
    slug: "tech-trends-2026-whats-changing-in-the-digital-world",
    title: "Tech Trends 2026: What's Changing in the Digital World",
    category: "Technology",
    thumbnail: "/src/assets/Blogs/tech-trends-2022-whats-changing-in-the-digital-world.webp",
    image: "/src/assets/Blogs/tech-trends-2022-whats-changing-in-the-digital-world.webp",
    date: "2026-03-05",
    author: "Tech Insider",
    excerpt: "Explore the biggest technology trends shaping 2026 – AI advancements, sustainable gadgets, Web3 evolution, and more.",
    readTime: "9 min",
    tags: ["tech trends", "technology", "AI", "gadgets", "innovation", "future tech", "digital world"],
    content: "Full article content goes here... Top 10 trends with explanations, real-world examples, and predictions on how they'll impact daily life and business."
  },
  {
    id: 2006,
    slug: "the-benefits-of-regular-exercise-for-a-healthy-lifestyle",
    title: "The Benefits of Regular Exercise for a Healthy Lifestyle",
    category: "Health & Fitness",
    thumbnail: "/src/assets/Blogs/the-benefits-of-regular-exercise-for-a-healthy-lifestyle.webp",
    image: "/src/assets/Blogs/the-benefits-of-regular-exercise-for-a-healthy-lifestyle.webp",
    date: "2026-01-20",
    author: "Fitness Coach",
    excerpt: "Why consistent physical activity is essential – from physical health improvements to mental well-being and longevity benefits.",
    readTime: "7 min",
    tags: ["exercise", "fitness", "healthy lifestyle", "health benefits", "workout", "wellness", "mental health"],
    content: "Full article content goes here... Physical benefits (heart health, strength), mental perks (stress reduction, mood boost), types of exercise, how to start, and common myths debunked."
  },
  {
    id: 2007,
    slug: "the-psychology-of-happiness-finding-joy-in-everyday-life",
    title: "The Psychology of Happiness: Finding Joy in Everyday Life",
    category: "Self-Improvement",
    thumbnail: "/src/assets/Blogs/the-psychology-of-happiness-finding-joy-in-everyday-life.webp",
    image: "/src/assets/Blogs/the-psychology-of-happiness-finding-joy-in-everyday-life.webp",
    date: "2026-02-25",
    author: "Mindful Writer",
    excerpt: "Science-backed insights into what truly makes us happy and practical ways to cultivate more joy in daily routines.",
    readTime: "11 min",
    tags: ["happiness", "psychology", "self-improvement", "mental health", "mindfulness", "positive thinking", "wellbeing"],
    content: "Full article content goes here... Key happiness theories (hedonic vs eudaimonic), gratitude practices, social connections, flow states, and daily habits for lasting joy."
  },
  {
    id: 2008,
    slug: "the-ultimate-guide-to-traveling-on-a-budget",
    title: "The Ultimate Guide to Traveling on a Budget",
    category: "Travel",
    thumbnail: "/src/assets/Blogs/the-ultimate-guide-to-traveling-on-a-budget.webp",
    image: "/src/assets/Blogs/the-ultimate-guide-to-traveling-on-a-budget.webp",
    date: "2026-03-10",
    author: "Wanderlust Pro",
    excerpt: "Expert tips, hacks, and strategies to explore the world affordably without sacrificing experiences or comfort.",
    readTime: "14 min",
    tags: ["travel", "budget travel", "cheap travel", "backpacking", "adventure", "travel tips", "wanderlust"],
    content: "Full article content goes here... Planning phase, finding cheap flights/accommodation, food/transport hacks, free activities, packing light, and real budget itineraries."
  }
];